version: '3.9'

services:
  web:
    build: .
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      mongod --quiet --logpath /dev/null
    environment:
      - "MONGO_INITDB_DATABASE=birthday_reminder"
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=password"
    env_file:
      - .env

  worker:
    build: .
    command: celery --app=app.tasks.worker.celery worker --loglevel=info --logfile=app/tasks/celery.log
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - mongodb

  redis:
    image: redis:latest
