version: '3.9'

services:
  redis:
    image: redis:latest

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      mongod --quiet --logpath /dev/null
    environment:
      - "MONGO_INITDB_DATABASE=birthday_reminder"
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=password"
    env_file:
      - .env

  web:
    build: .
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_beat:
    build: .
    command: celery -A app.tasks.worker beat --loglevel=info --logfile=app/tasks/celery.log
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - mongodb

  celery_worker:
    build: .
    command: celery -A app.tasks.worker worker --loglevel=info --logfile=app/tasks/celery.log
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - mongodb

  celery_flower:
    build: .
    command: celery -A app.tasks.worker flower --loglevel=info --port=5566 --basic_auth=admin:admin
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
      - mongodb
    ports:
      - "5566:5566"